import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { NeoMLGeneratedModule, NeoMlGeneratedSharedModule } from './generated/module.js';
import { NeoMlValidator, registerValidationChecks } from './neo-ml-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type NeoMlAddedServices = {
    validation: {
        NeoMlValidator: NeoMlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type NeoMlServices = LangiumServices & NeoMlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const NeoMlModule: Module<NeoMlServices, PartialLangiumServices & NeoMlAddedServices> = {
    validation: {
        NeoMlValidator: () => new NeoMlValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createNeoMlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    NeoMl: NeoMlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        NeoMlGeneratedSharedModule
    );
    const NeoMl = inject(
        createDefaultModule({ shared }),
        NeoMLGeneratedModule,
        NeoMlModule
    );
    shared.ServiceRegistry.register(NeoMl);
    registerValidationChecks(NeoMl);
    return { shared, NeoMl };
}
